version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.7.3
    container_name: grape-graphdb
    ports:
      - "7200:7200"
    volumes:
      - ./data/graphdb-home:/opt/graphdb/home
      - ./data/graphdb-import:/root/graphdb-import
      - ./kg_example:/kg_example:ro
    environment:
      GDB_JAVA_OPTS: "-Xmx2g -Xms1g"
    networks:
      - grape-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/rest/repositories"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  grape-network:
    driver: bridge
